### ISSUE TITLE
Reseed fails on Debian Sid (unstable)

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#210]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

First reported by @EinMByte, this appears to be specific to Debian Jessie (all tests pass and Reseed is fully functional on Arch and Ubuntu Wily/Trusty).

Output (omitting passing tests):
> kovri/src/tests/unit_tests/core/Reseed.cpp(254): error in "GoodSU3": check su3.SU3Impl() failed
*** 1 failure detected in test suite "Master Test Suite"

Build info:
> -- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test CXX14_SUPPORTED
-- Performing Test CXX14_SUPPORTED - Success
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   chrono
--   log
--   program_options
--   date_time
--   thread
--   system
--   filesystem
--   regex
-- Found Crypto++: /usr/include, /usr/lib/libcryptopp.so
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1t") 
-- Found MiniUPnP headers: /usr/include/miniupnpc
-- ---------------------------------------                                                                                                  [103/359]
-- Build type         : Debug
-- Compiler vendor    : GNU
-- Compiler version   : 4.9.2
-- Compiler path      : /usr/bin/c++
-- Install prefix:    : /usr/local
-- Kovri data directory: /home/kovri/.kovri
-- Options:
--   BENCHMARKS       : ON
--   BINARY           : ON
--   CRYPTOPP         : ON
--   DOXYGEN          : OFF
--   HARDENING        : OFF
--   LIBRARY          : ON
--   OPTIMIZATION     : OFF
--   STATIC BUILD     : OFF
--   SUPERCOP         : ON
--   TESTS            : ON
--   UPnP             : OFF
-- ---------------------------------------
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   unit_test_framework
--   chrono
--   program_options
--   date_time
--   thread
--   system
--   filesystem
--   regex
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kovri/build

A very crude hypothesis (until I look into this further): the issue may be related to compiler version and how we initialize ```SU3FixtureImpl```'s ```byte``` argument (our suggested gcc minimum requirement is 5.3.0).

Note: there is currently a Jessie bug with CMake and OpenSSL as reported [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826656) (opened less than 2 weeks ago) which prevents CMake from working. A simple work-around is provided in the link.

**Comment by EinMByte** [comment]
More complete log of `./kovri-tests`:
```
$ ./kovri-tests
...
default:default		DBG		SU3: preparation successful
default:default		DBG		SU3: verifying stream...
default:default		ERR		SU3: signature failed
default:default		ERR		SU3: verification failed
kovri-tests: asn.cpp:415: virtual CryptoPP::BERGeneralDecoder::~BERGeneralDecoder(): Assertion `0' failed.
unknown location(0): fatal error in "GoodX509": signal: SIGABRT (application abort requested)
/kovri/src/tests/unit_tests/core/crypto/util/X509.cpp(97): last checkpoint
default:default		ERR		X509: certificate is not PEM
default:default		ERR		X509: failed to process certificate
default:default		ERR		X509: certificate is not PEM
default:default		ERR		X509: failed to process certificate
kovri-tests: asn.cpp:415: virtual CryptoPP::BERGeneralDecoder::~BERGeneralDecoder(): Assertion `0' failed.
unknown location(0): fatal error in "BadContent": signal: SIGABRT (application abort requested)
/kovri/src/tests/unit_tests/core/crypto/util/X509.cpp(119): last checkpoint
default:default		DBG		ZIP: preparing local file...
default:default		DBG		ZIP: successfully prepared file
default:default		DBG		ZIP: decompressing local file...
default:default		DBG		ZIP: processing file routerInfo-1mAmAGGkmTwdgiDQUMy7UUO9qxcVSssWZL3qbScQrIg=.dat 648 bytes
default:default		DBG		ZIP: file uses compression method 'deflate'
default:default		DBG		ZIP: successfully processed file
default:default		DBG		ZIP: successfully unzipped stream
default:default		ERR		ZIP: missing central directory header
default:default		DBG		ZIP: preparing local file...
default:default		ERR		ZIP: archive data descriptor not found
default:default		DBG		ZIP: preparing local file...
default:default		DBG		ZIP: successfully prepared file
default:default		DBG		ZIP: decompressing local file...
default:default		DBG		ZIP: processing file routerInfo-1mAmAGGkmTwdgiDQUMy7UUO9qxcVSssWZL3qbScQrIg=.dat 648 bytes
default:default		ERR		ZIP: file uses an unsupported compression method
default:default		DBG		ZIP: preparing local file...
default:default		DBG		ZIP: successfully prepared file
default:default		DBG		ZIP: decompressing local file...
default:default		DBG		ZIP: processing file routerInfo-1mAmAGGkmTwdgiDQUMy7UUO9qxcVSssWZL3qbScQrIg=.dat 648 bytes
default:default		DBG		ZIP: file uses compression method 'deflate'
default:default		ERR		ZIP: CRC-32 Failed
default:default		DBG		ZIP: preparing local file...
default:default		DBG		ZIP: successfully prepared file
default:default		DBG		ZIP: decompressing local file...
default:default		DBG		ZIP: processing file routerInfo-1mAmAGGkmTwdgiDQUMy7UUO9qxcVSssWZL3qbScQrIg=.dat 577 bytes
default:default		DBG		ZIP: file uses compression method 'deflate'
default:default		ERR		DeflateDecompressorImpl: Put() caught exception 'Inflator: unexpected end of compressed block'
default:default		ERR		ZIP: CRC-32 Failed
default:default		DBG		ZIP: preparing local file...
default:default		DBG		ZIP: successfully prepared file
default:default		DBG		ZIP: decompressing local file...
default:default		DBG		ZIP: processing file routerInfo-1mAmAGGkmTwdgiDQUMy7UUO9qxcVSssWZL3qbScQrIg=.dat 648 bytes
default:default		DBG		ZIP: file uses compression method 'deflate'
default:default		ERR		ZIP: actual uncompressed size 671 exceeds 577 from header
default:default		DBG		ZIP: preparing local file...
default:default		ERR		ZIP: archived filename length not appropriate: 65

*** 2 failures detected in test suite "Master Test Suite"
```

**Comment by EinMByte** [comment]
I've labeled this as critical because it also causes a crash on startup if new keys have to be generated.

**Comment by EinMByte** [comment]
It seems to be a Crypto++ bug: the `BERGeneralDecoder` destructor had an `assert 0;` line.
This was fixed in [this commit](https://github.com/weidai11/cryptopp/commit/bb3276389e445117d1592d31a777070381aefa5f#diff-5e0f7463043d19c9c331a17ddd331dd7).

**Comment by EinMByte** [comment]
I fail to see why the debian repositories only contain a `-dev` package for crypto++, which has assertions enabled.
Current workaround is to use a custom crypto++ installation.

**Comment by anonimal** [comment]
System (freshly updated):
```bash
$ uname -a
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
```
Kovri master https://github.com/monero-project/kovri/commit/b078bd53f71b68ed21ab208cc483eb90d6cbc18c built and tested against:
```bash
$ dpkg -l libcrypto++-dev | tail -n1
ii  libcrypto++-dev 5.6.1-6+deb8u2 amd64        General purpose cryptographic library - C++ development
```
- fresh github clone (https://github.com/weidai11/cryptopp/commit/ed625338d3fc0a8518056f3bebfccb0b1bebf9ad)
- https://github.com/weidai11/cryptopp/commit/bb3276389e445117d1592d31a777070381aefa5f
- https://github.com/weidai11/cryptopp/commit/1743b976f7b5e6c67cc9288afa27a3b08a84dd38

On fresh startup, produces no crash (though Reseed will fail as expected):
```bash
$ rm -fr ~/.kovri/ && cd ~/kovri/build/ && rm -fr CMake* && cmake ../ && time make -j4 && ./kovri
```
```
2016:06:20|21:11:27.076408|NFO   Crypto: checking for AES-NI...
2016:06:20|21:11:27.077762|NFO   Crypto: AES-NI is available!
2016:06:20|21:11:27.078891|NFO   The Kovri I2P Router Project
2016:06:20|21:11:27.079714|NFO   Version 0.1.0-pre-alpha
2016:06:20|21:11:27.082423|NFO   Daemon_Singleton: initializing
2016:06:20|21:11:27.129812|NFO   Daemon_Singleton: 1 I2P client tunnels created
2016:06:20|21:11:27.130255|NFO   Daemon_Singleton: 0 I2P server tunnels created
2016:06:20|21:11:27.130851|NFO   Daemon_Singleton: listening on port 9559
Not opening log file: 
2016:06:20|21:11:27.131380|NFO   Daemon_Singleton: starting NetDb
2016:06:20|21:11:27.133666|NFO   NetDb: 0 routers loaded
2016:06:20|21:11:27.134008|NFO   NetDb: 0 floodfills loaded
2016:06:20|21:11:27.134534|DBG   Reseed: processing certificates...
2016:06:20|21:11:27.135439|DBG   Reseed: acquiring signing key from "/home/kovri/.kovri/certificates/su3/bugme_at_mail.i2p.crt"
2016:06:20|21:11:27.136144|DBG   X509: successfully processed certificate
2016:06:20|21:11:27.136845|DBG   X509: successfully acquired signing key
2016:06:20|21:11:27.137325|DBG   Reseed: acquiring signing key from "/home/kovri/.kovri/certificates/su3/matt_at_drollette.com.crt"
2016:06:20|21:11:27.137798|DBG   X509: successfully processed certificate
2016:06:20|21:11:27.138214|DBG   X509: successfully acquired signing key
2016:06:20|21:11:27.138978|DBG   Reseed: acquiring signing key from "/home/kovri/.kovri/certificates/su3/zmx_at_mail.i2p.crt"
2016:06:20|21:11:27.140246|DBG   X509: successfully processed certificate
2016:06:20|21:11:27.140506|DBG   X509: successfully acquired signing key
2016:06:20|21:11:27.140981|DBG   Reseed: acquiring signing key from "/home/kovri/.kovri/certificates/su3/meeh_at_mail.i2p.crt"
2016:06:20|21:11:27.141434|DBG   X509: successfully processed certificate
2016:06:20|21:11:27.142063|DBG   X509: successfully acquired signing key
2016:06:20|21:11:27.142381|DBG   Reseed: acquiring signing key from "/home/kovri/.kovri/certificates/su3/parg_at_mail.i2p.crt"
2016:06:20|21:11:27.143388|DBG   X509: successfully processed certificate
2016:06:20|21:11:27.143992|DBG   X509: successfully acquired signing key
2016:06:20|21:11:27.144456|DBG   Reseed: acquiring signing key from "/home/kovri/.kovri/certificates/su3/echelon_at_mail.i2p.crt"
2016:06:20|21:11:27.145255|DBG   X509: successfully processed certificate
2016:06:20|21:11:27.145496|DBG   X509: successfully acquired signing key
2016:06:20|21:11:27.146169|DBG   Reseed: acquiring signing key from "/home/kovri/.kovri/certificates/su3/backup_at_mail.i2p.crt"
2016:06:20|21:11:27.146834|DBG   X509: successfully processed certificate
2016:06:20|21:11:27.147041|DBG   X509: successfully acquired signing key
2016:06:20|21:11:27.147570|NFO   Reseed: successfuly loaded 7 certificates
2016:06:20|21:11:27.148094|NFO   Reseed: fetching stream from https://reseed.i2p-projekt.de/i2pseeds.su3
2016:06:20|21:11:28.990907|NFO   HTTP: Connected to reseed.i2p-projekt.de:443
2016:06:20|21:11:29.478795|NFO   Reseed: fetch successful
2016:06:20|21:11:29.479425|DBG   SU3: preparing stream...
2016:06:20|21:11:29.479729|DBG   SU3: found reseed data
2016:06:20|21:11:29.485037|ERR   SU3: invalid signer ID
2016:06:20|21:11:29.485438|ERR   SU3: preparation failed
2016:06:20|21:11:29.485792|ERR   Reseed: SU3 implementation failed
2016:06:20|21:11:29.486378|ERR   NetDb: reseed failed
2016:06:20|21:11:29.486861|ERR   Daemon_Singleton: NetDb failed to start
2016:06:20|21:11:29.487501|NFO   Daemon_Singleton: stopping client
2016:06:20|21:11:29.488284|NFO   ClientContext: HTTP Proxy stopped
2016:06:20|21:11:29.489538|NFO   ClientContext: SOCKS Proxy stopped
2016:06:20|21:11:29.490551|NFO   ClientContext: I2P client tunnel on port 6669 stopped
2016:06:20|21:11:29.492416|NFO   Daemon_Singleton: stopping tunnels
2016:06:20|21:11:29.492756|NFO   Daemon_Singleton: stopping transports
2016:06:20|21:11:29.493005|NFO   Daemon_Singleton: stopping NetDb
2016:06:20|21:11:29.493239|NFO   Goodbye!
```

For tests, no fatal errors but still produces:
```bash
$ rm -fr ~/.kovri/ && cd ~/kovri/build/ && rm -fr CMake* && cmake -DWITH_TESTS=ON -DWITH_BENCHMARKS=ON ../ && time make -j4 && ./kovri-tests
```
```
2016:06:20|21:18:27.552543|NFO   Crypto: checking for AES-NI...
2016:06:20|21:18:27.553633|NFO   Crypto: AES-NI is available!
Running 69 test cases...
2016:06:20|21:18:27.555375|DBG   SU3: preparing stream...
2016:06:20|21:18:27.556038|DBG   SU3: found reseed data
2016:06:20|21:18:27.563889|ERR   SU3: invalid signer ID
2016:06:20|21:18:27.564341|ERR   SU3: preparation failed
/home/kovri/kovri/src/tests/unit_tests/core/Reseed.cpp(254): error in "GoodSU3": check su3.SU3Impl() failed
2016:06:20|21:18:27.565186|DBG   SU3: preparing stream...
2016:06:20|21:18:27.565727|ERR   SU3: invalid magic value
2016:06:20|21:18:27.566489|ERR   SU3: preparation failed
2016:06:20|21:18:27.567463|DBG   SU3: preparing stream...
2016:06:20|21:18:27.568053|ERR   SU3: signature type not supported
2016:06:20|21:18:27.568805|ERR   SU3: preparation failed
2016:06:20|21:18:27.569740|DBG   SU3: preparing stream...
2016:06:20|21:18:27.570122|ERR   SU3: invalid signature length
2016:06:20|21:18:27.570987|ERR   SU3: preparation failed
2016:06:20|21:18:27.571745|DBG   SU3: preparing stream...
2016:06:20|21:18:27.573251|ERR   SU3: version length too short
2016:06:20|21:18:27.573646|ERR   SU3: preparation failed
2016:06:20|21:18:27.574404|DBG   SU3: preparing stream...
2016:06:20|21:18:27.574808|ERR   SU3: invalid signer ID length
2016:06:20|21:18:27.575455|ERR   SU3: preparation failed
2016:06:20|21:18:27.576264|DBG   SU3: preparing stream...
2016:06:20|21:18:27.576719|ERR   SU3: invalid content length
2016:06:20|21:18:27.577400|ERR   SU3: preparation failed
2016:06:20|21:18:27.578276|DBG   SU3: preparing stream...
2016:06:20|21:18:27.578708|ERR   SU3: invalid file type 4
2016:06:20|21:18:27.579168|ERR   SU3: preparation failed
2016:06:20|21:18:27.580123|DBG   SU3: preparing stream...
2016:06:20|21:18:27.580539|ERR   SU3: invalid content type 5
2016:06:20|21:18:27.581075|ERR   SU3: preparation failed
2016:06:20|21:18:27.581894|DBG   SU3: preparing stream...
2016:06:20|21:18:27.582202|DBG   SU3: found reseed data
2016:06:20|21:18:27.587470|ERR   SU3: invalid signer ID
2016:06:20|21:18:27.588043|ERR   SU3: preparation failed
2016:06:20|21:18:27.588705|DBG   SU3: preparing stream...
2016:06:20|21:18:27.589020|DBG   SU3: found reseed data
2016:06:20|21:18:27.593545|ERR   SU3: invalid signer ID
2016:06:20|21:18:27.594005|ERR   SU3: preparation failed
2016:06:20|21:18:27.594588|DBG   SU3: preparing stream...
2016:06:20|21:18:27.594950|DBG   SU3: found reseed data
2016:06:20|21:18:27.598859|ERR   SU3: invalid signer ID
2016:06:20|21:18:27.599318|ERR   SU3: preparation failed
2016:06:20|21:18:27.601102|DBG   SU3: preparing stream...
2016:06:20|21:18:27.601471|DBG   SU3: found reseed data
2016:06:20|21:18:27.608514|ERR   SU3: invalid signer ID
2016:06:20|21:18:27.609110|ERR   SU3: preparation failed
2016:06:20|21:18:27.746200|DBG   X509: successfully processed certificate
2016:06:20|21:18:27.747022|DBG   X509: successfully acquired signing key
2016:06:20|21:18:27.747811|ERR   X509: certificate is not PEM
2016:06:20|21:18:27.748561|ERR   X509: failed to process certificate
2016:06:20|21:18:27.749279|ERR   X509: certificate is not PEM
2016:06:20|21:18:27.749893|ERR   X509: failed to process certificate
2016:06:20|21:18:27.750903|ERR   X509: PEM decoding exception 'BER decode error'
2016:06:20|21:18:27.751602|ERR   X509: failed to decode certificate
2016:06:20|21:18:27.752278|ERR   X509: failed to process certificate
2016:06:20|21:18:27.754314|DBG   ZIP: preparing local file...
2016:06:20|21:18:27.754673|DBG   ZIP: successfully prepared file
2016:06:20|21:18:27.755148|DBG   ZIP: decompressing local file...
2016:06:20|21:18:27.755967|DBG   ZIP: processing file routerInfo-1mAmAGgkmTwdgiDQUMy7UUO9qxcVSssWZL3qbScQrIg=.dat 648 bytes
2016:06:20|21:18:27.756574|DBG   ZIP: file uses compression method 'deflate'
2016:06:20|21:18:27.757415|DBG   ZIP: successfully processed file
2016:06:20|21:18:27.757846|DBG   ZIP: successfully unzipped stream
2016:06:20|21:18:27.758535|ERR   ZIP: missing central directory header
2016:06:20|21:18:27.759084|DBG   ZIP: preparing local file...
2016:06:20|21:18:27.759593|ERR   ZIP: archive data descriptor not found
2016:06:20|21:18:27.760304|DBG   ZIP: preparing local file...
2016:06:20|21:18:27.760611|DBG   ZIP: successfully prepared file
2016:06:20|21:18:27.761361|DBG   ZIP: decompressing local file...
2016:06:20|21:18:27.761791|DBG   ZIP: processing file routerInfo-1mAmAGgkmTwdgiDQUMy7UUO9qxcVSssWZL3qbScQrIg=.dat 648 bytes
2016:06:20|21:18:27.762167|ERR   ZIP: file uses an unsupported compression method
2016:06:20|21:18:27.762771|DBG   ZIP: preparing local file...
2016:06:20|21:18:27.763088|DBG   ZIP: successfully prepared file
2016:06:20|21:18:27.763447|DBG   ZIP: decompressing local file...
2016:06:20|21:18:27.764116|DBG   ZIP: processing file routerInfo-1mAmAGgkmTwdgiDQUMy7UUO9qxcVSssWZL3qbScQrIg=.dat 648 bytes
2016:06:20|21:18:27.764397|DBG   ZIP: file uses compression method 'deflate'
2016:06:20|21:18:27.764913|ERR   ZIP: CRC-32 Failed
2016:06:20|21:18:27.765538|DBG   ZIP: preparing local file...
2016:06:20|21:18:27.765820|DBG   ZIP: successfully prepared file
2016:06:20|21:18:27.766239|DBG   ZIP: decompressing local file...
2016:06:20|21:18:27.766715|DBG   ZIP: processing file routerInfo-1mAmAGgkmTwdgiDQUMy7UUO9qxcVSssWZL3qbScQrIg=.dat 577 bytes
2016:06:20|21:18:27.766999|DBG   ZIP: file uses compression method 'deflate'
2016:06:20|21:18:27.767383|ERR   ZIP: CRC-32 Failed
2016:06:20|21:18:27.768146|DBG   ZIP: preparing local file...
2016:06:20|21:18:27.768448|DBG   ZIP: successfully prepared file
2016:06:20|21:18:27.768844|DBG   ZIP: decompressing local file...
2016:06:20|21:18:27.769304|DBG   ZIP: processing file routerInfo-1mAmAGgkmTwdgiDQUMy7UUO9qxcVSssWZL3qbScQrIg=.dat 648 bytes
2016:06:20|21:18:27.769781|DBG   ZIP: file uses compression method 'deflate'
2016:06:20|21:18:27.770272|ERR   ZIP: actual uncompressed size 671 exceeds 577 from header
2016:06:20|21:18:27.771066|DBG   ZIP: preparing local file...
2016:06:20|21:18:27.771463|ERR   ZIP: archived filename length not appropriate: 65

*** 1 failure detected in test suite "Master Test Suite"
```

:confused:

**Comment by EinMByte** [comment]
Make sure to build **without** `-DNDEBUG`.

**Comment by anonimal** [comment]
Bingo.

> latest version from github, or with -DNDEBUG

I thought "or" was optional - it should be "and" (if building before weidai11/cryptopp@bb32763) :blush:

Building against weidai11/cryptopp@bb32763 and master **does** fix the dtor/SIGABRT issue but the original issue still stands (failed ```GoodSU3``` and failure to reseed). Can you reproduce that portion of the issue?

**Comment by EinMByte** [comment]
@anonimal All tests passing on my fork, maybe it's due to some recent changes?

**Comment by anonimal** [comment]
As reported in ```#monero-dev``` by moneromooo, this also effects Fedora 21.

Both the binary *and* tests produce the results seen in https://github.com/monero-project/kovri/issues/210#issuecomment-227264802.

**Comment by anonimal** [comment]
#220 fixed Fedora. Now we need to test against Debian.

**Comment by anonimal** [comment]
#220 also fixes a fresh, vanilla Debian Jessie (I still can't reproduce those assertions with libcrypto++-dev 5.6.1-6+deb8u2).

**Comment by anonimal** [comment]
@EinMByte I'm able to reproduce the assertions on Debian unstable - but this ticket was specifically for Jessie. What sources are you pulling from for apt?

**Comment by EinMByte** [comment]
@anonimal 
`ii  libcrypto++-dev 5.6.3-6      amd64        General purpose cryptographic library - C++ development`

**Comment by anonimal** [comment]
[Indeed](https://packages.debian.org/sid/libcrypto++-dev). Shall we rename ticket to ```Reseed fails on Debian Sid (unstable)``` or similar?

**Comment by EinMByte** [comment]
@anonimal Yes, indeed.

**Comment by anonimal** [comment]
```
2016-07-22     &anonimal       EinMByte: Hi. I'm wondering if we should add a crypto++ submodule in order to resolve #210.
2016-07-22     &anonimal       Testing if system is relevent ubuntu would be trivial; either in cmake or the makefile.
2016-07-22     &anonimal       EinMByte: on 2nd thought, I *really* would like to do that because of that compression issue I had to fix a while back.
2016-07-22     &anonimal       They've fixed it and its sitting in their repo.
2016-07-22     &anonimal       And who knows when they will have their next release.
2016-07-22     &anonimal       Of course there is the question of stability, but we can work off a specific commit and see how she runs.
2016-07-22      *      anonimal would rather work with them than against them (e.g., crypto_refactor)
```

Also, there is the question of security - but we are still in pre-alpha. And by the time cryptopp has another release... we may be in beta.

I'm not too attached to the idea but I like the idea of becoming more involved with cryptopp through kovri. Also, they're getting a lot of work done lately.

I'm open to thoughts.

Referencing #141.
